import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
    console.log("🌱 Seeding database...");

    // Create a superuser
    const hashedPassword = await bcrypt.hash("admin123", 12);
    
    const superuser = await prisma.user.upsert({
        where: { email: "admin@templebook.com" },
        update: {},
        create: {
            email: "admin@templebook.com",
            password: hashedPassword,
            name: "System Admin",
            phone: "+91 9876543210",
            role: "SUPERUSER",
            isApproved: true,
        },
    });
    console.log("✅ Created superuser:", superuser.email);

    // Create a temple board member
    const templeBoardPassword = await bcrypt.hash("temple123", 12);
    
    const templeBoard = await prisma.user.upsert({
        where: { email: "board@templebook.com" },
        update: {},
        create: {
            email: "board@templebook.com",
            password: templeBoardPassword,
            name: "Temple Board Manager",
            phone: "+91 9876543211",
            role: "TEMPLE_BOARD",
            isApproved: true,
        },
    });
    console.log("✅ Created temple board user:", templeBoard.email);

    // Create a regular user
    const userPassword = await bcrypt.hash("user123", 12);
    
    const regularUser = await prisma.user.upsert({
        where: { email: "user@templebook.com" },
        update: {},
        create: {
            email: "user@templebook.com",
            password: userPassword,
            name: "Devotee User",
            phone: "+91 9876543212",
            role: "USER",
            isApproved: true,
        },
    });
    console.log("✅ Created regular user:", regularUser.email);

    // Sample temples data
    const templesData = [
        {
            name: "Shri Siddhivinayak Temple",
            description: "One of the most famous Ganesh temples in Mumbai. The temple is dedicated to Lord Ganesha and attracts thousands of devotees daily. The idol is believed to be 'Swayambhu' (self-manifested) and is said to fulfill the wishes of devotees.",
            location: "Prabhadevi, Mumbai",
            address: "SK Bole Marg, Prabhadevi",
            city: "Mumbai",
            state: "Maharashtra",
            pincode: "400028",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:30 AM - 10:00 PM",
            dailyTicketLimit: 500,
            ticketPrice: 0,
        },
        {
            name: "Shri Kashi Vishwanath Temple",
            description: "One of the most famous Hindu temples dedicated to Lord Shiva. Located on the western bank of the holy river Ganga, it is one of the twelve Jyotirlingas. The temple has been a center of Hindu worship and culture for centuries.",
            location: "Varanasi, Uttar Pradesh",
            address: "Lahori Tola, Varanasi",
            city: "Varanasi",
            state: "Uttar Pradesh",
            pincode: "221001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "3:00 AM - 11:00 PM",
            dailyTicketLimit: 1000,
            ticketPrice: 50,
        },
        {
            name: "Tirumala Venkateswara Temple",
            description: "One of the richest and most visited temples in the world, dedicated to Lord Venkateswara. Located in the hill town of Tirumala at Tirupati. The temple is the most visited place of worship in the world.",
            location: "Tirumala, Andhra Pradesh",
            address: "Tirumala Hills, Tirupati",
            city: "Tirupati",
            state: "Andhra Pradesh",
            pincode: "517504",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "2:30 AM - 1:30 AM (Next Day)",
            dailyTicketLimit: 5000,
            ticketPrice: 300,
        },
        {
            name: "Golden Temple (Harmandir Sahib)",
            description: "The holiest Gurdwara and the most important pilgrimage site of Sikhism. Known for its golden facade and spiritual atmosphere. The temple serves free meals (langar) to over 100,000 people daily.",
            location: "Amritsar, Punjab",
            address: "Golden Temple Road, Amritsar",
            city: "Amritsar",
            state: "Punjab",
            pincode: "143001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "Open 24 Hours",
            dailyTicketLimit: 2000,
            ticketPrice: 0,
        },
        {
            name: "Jagannath Temple",
            description: "A famous Hindu temple dedicated to Lord Jagannath, a form of Vishnu. One of the four sacred pilgrimage centers (Char Dham). Famous for the annual Rath Yatra festival.",
            location: "Puri, Odisha",
            address: "Grand Road, Puri",
            city: "Puri",
            state: "Odisha",
            pincode: "752001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 11:00 PM",
            dailyTicketLimit: 800,
            ticketPrice: 25,
        },
        {
            name: "Meenakshi Amman Temple",
            description: "A historic Hindu temple located on the southern bank of the Vaigai River. Dedicated to Goddess Meenakshi and Lord Sundareswarar. Known for its stunning Dravidian architecture and colorful gopurams.",
            location: "Madurai, Tamil Nadu",
            address: "Madurai Main Road",
            city: "Madurai",
            state: "Tamil Nadu",
            pincode: "625001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 12:30 PM, 4:00 PM - 10:00 PM",
            dailyTicketLimit: 600,
            ticketPrice: 20,
        },
        {
            name: "Vaishno Devi Temple",
            description: "A Hindu pilgrimage site in the Trikuta Mountains. Dedicated to Vaishno Devi, an incarnation of Goddess Durga. The temple is located in a cave and attracts millions of devotees annually.",
            location: "Katra, Jammu and Kashmir",
            address: "Vaishno Devi Road, Katra",
            city: "Katra",
            state: "Jammu and Kashmir",
            pincode: "190201",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "4:00 AM - 8:00 PM",
            dailyTicketLimit: 2000,
            ticketPrice: 100,
        },
        {
            name: "Kedarnath Temple",
            description: "One of the most sacred Hindu temples dedicated to Lord Shiva. Located in the Himalayas, it is one of the twelve Jyotirlingas and part of the Char Dham pilgrimage route.",
            location: "Kedarnath, Uttarakhand",
            address: "Kedarnath Valley",
            city: "Kedarnath",
            state: "Uttarakhand",
            pincode: "246421",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 8:00 PM",
            dailyTicketLimit: 400,
            ticketPrice: 50,
        },
        {
            name: "Badrinath Temple",
            description: "A sacred Hindu temple dedicated to Lord Vishnu. One of the most important pilgrimage centers in India and part of the Char Dham circuit. Located in the Himalayas.",
            location: "Badrinath, Uttarakhand",
            address: "Badrinath Valley",
            city: "Badrinath",
            state: "Uttarakhand",
            pincode: "246422",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 9:00 PM",
            dailyTicketLimit: 350,
            ticketPrice: 60,
        },
        {
            name: "Dwarka Dwarkadhish Temple",
            description: "A significant Hindu temple dedicated to Lord Krishna. Located in Dwarka, Gujarat, it is one of the four cardinal spiritual centers in Hinduism (Char Dham).",
            location: "Dwarka, Gujarat",
            address: "Dwarka Main Road",
            city: "Dwarka",
            state: "Gujarat",
            pincode: "361335",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 9:30 PM",
            dailyTicketLimit: 450,
            ticketPrice: 40,
        },
        {
            name: "Ramnath Temple",
            description: "A sacred temple dedicated to Lord Rama located on the bank of the Saryu River. Associated with the Ramayana epic.",
            location: "Ayodhya, Uttar Pradesh",
            address: "Ram Mandir Complex",
            city: "Ayodhya",
            state: "Uttar Pradesh",
            pincode: "224001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 10:00 PM",
            dailyTicketLimit: 600,
            ticketPrice: 30,
        },
        {
            name: "Somnath Temple",
            description: "One of the twelve Jyotirlingas dedicated to Lord Shiva. Located in Gujarat on the coast of the Arabian Sea. Known for its architectural beauty and spiritual significance.",
            location: "Veraval, Gujarat",
            address: "Somnath Temple Road",
            city: "Veraval",
            state: "Gujarat",
            pincode: "362268",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 9:00 PM",
            dailyTicketLimit: 380,
            ticketPrice: 35,
        },
        {
            name: "Amarnath Cave Temple",
            description: "A sacred Hindu shrine dedicated to Lord Shiva located high in the Himalayas. The cave contains an ice stalactite believed to be a manifestation of Shiva.",
            location: "Srinagar, Jammu and Kashmir",
            address: "Amarnath Cave Road",
            city: "Srinagar",
            state: "Jammu and Kashmir",
            pincode: "190001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 7:00 PM",
            dailyTicketLimit: 300,
            ticketPrice: 75,
        },
        {
            name: "Birla Mandir, Delhi",
            description: "A modern Hindu temple in New Delhi dedicated to Lord Krishna and Radha. Built by the Birla family, it showcases modern Hindu architecture.",
            location: "Delhi Cantt, Delhi",
            address: "Mandir Marg, New Delhi",
            city: "Delhi",
            state: "Delhi",
            pincode: "110001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 9:00 PM",
            dailyTicketLimit: 400,
            ticketPrice: 0,
        },
        {
            name: "Sri Ranganathaswamy Temple",
            description: "One of the largest temples in the world dedicated to Lord Vishnu. Located on an island in the Kaveri River in Tamil Nadu. Known for its intricate Dravidian architecture.",
            location: "Srirangam, Tamil Nadu",
            address: "Srirangam Main Road",
            city: "Tiruchirapalli",
            state: "Tamil Nadu",
            pincode: "620006",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "4:00 AM - 1:00 PM, 2:00 PM - 8:30 PM",
            dailyTicketLimit: 500,
            ticketPrice: 25,
        },
        {
            name: "Kailasanath Temple",
            description: "An ancient Hindu temple dedicated to Lord Shiva located in Kanchipuram. Known for its magnificent carved stone architecture.",
            location: "Kanchipuram, Tamil Nadu",
            address: "East Raja Street, Kanchipuram",
            city: "Kanchipuram",
            state: "Tamil Nadu",
            pincode: "631502",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 12:00 PM, 4:00 PM - 8:00 PM",
            dailyTicketLimit: 300,
            ticketPrice: 15,
        },
        {
            name: "Brihadeeswarar Temple",
            description: "A Hindu temple dedicated to Lord Shiva located in Thanjavur. Built in the 11th century, it is a masterpiece of Chola dynasty architecture.",
            location: "Thanjavur, Tamil Nadu",
            address: "Thanjavur Temple Road",
            city: "Thanjavur",
            state: "Tamil Nadu",
            pincode: "613001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 12:00 PM, 3:00 PM - 8:00 PM",
            dailyTicketLimit: 250,
            ticketPrice: 20,
        },
        {
            name: "Sri Ekambaranathar Temple",
            description: "An ancient Hindu temple dedicated to Lord Shiva located in Kanchipuram. One of the oldest temples with beautiful Dravidian architecture.",
            location: "Kanchipuram, Tamil Nadu",
            address: "Ekambaranathar Temple Road",
            city: "Kanchipuram",
            state: "Tamil Nadu",
            pincode: "631502",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 12:00 PM, 4:00 PM - 8:30 PM",
            dailyTicketLimit: 280,
            ticketPrice: 15,
        },
        {
            name: "Parthasarathy Temple",
            description: "A Hindu temple dedicated to Lord Krishna located in Chennai. One of the oldest temples in South India with rich architectural heritage.",
            location: "Triplicane, Chennai",
            address: "Parthasarathy Temple Road",
            city: "Chennai",
            state: "Tamil Nadu",
            pincode: "600005",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 12:00 PM, 4:00 PM - 9:00 PM",
            dailyTicketLimit: 350,
            ticketPrice: 10,
        },
        {
            name: "Kapaleeshwarar Temple",
            description: "A Hindu temple dedicated to Lord Shiva located in Mylapore, Chennai. Known for its beautiful Dravidian gopurams and peacocks in the temple.",
            location: "Mylapore, Chennai",
            address: "Kapaleeshwarar Temple Road",
            city: "Chennai",
            state: "Tamil Nadu",
            pincode: "600004",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 12:00 PM, 4:00 PM - 9:00 PM",
            dailyTicketLimit: 400,
            ticketPrice: 10,
        },
        {
            name: "Jambukeshwarar Temple",
            description: "A Hindu temple dedicated to Lord Shiva located in Tiruvanaikaval. One of the five elemental lingams (Pancha Bootha Sthalams).",
            location: "Tiruvanaikaval, Tamil Nadu",
            address: "Jambukeshwarar Temple Road",
            city: "Tiruchirapalli",
            state: "Tamil Nadu",
            pincode: "620003",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:30 AM - 12:00 PM, 4:00 PM - 8:00 PM",
            dailyTicketLimit: 320,
            ticketPrice: 15,
        },
        {
            name: "Arunachaleswarar Temple",
            description: "A Hindu temple dedicated to Lord Shiva located in Tiruvannamalai. The temple is at the foot of the sacred Arunachala mountain.",
            location: "Tiruvannamalai, Tamil Nadu",
            address: "Arunachaleswarar Temple Road",
            city: "Tiruvannamalai",
            state: "Tamil Nadu",
            pincode: "606601",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 1:00 PM, 3:00 PM - 8:30 PM",
            dailyTicketLimit: 440,
            ticketPrice: 20,
        },
        {
            name: "Sabarimala Ayyappa Temple",
            description: "A major pilgrimage destination for Lord Ayyappa. Located in the Western Ghats, it attracts millions of devotees, especially during the pilgrimage season.",
            location: "Pathanamthitta, Kerala",
            address: "Sabarimala Temple Road",
            city: "Pathanamthitta",
            state: "Kerala",
            pincode: "689647",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 11:00 PM",
            dailyTicketLimit: 800,
            ticketPrice: 50,
        },
        {
            name: "Guruvayur Sri Krishna Temple",
            description: "A major Hindu temple dedicated to Lord Krishna located in Kerala. Known as the Dwarka of South India.",
            location: "Guruvayur, Kerala",
            address: "Guruvayur Temple Road",
            city: "Guruvayur",
            state: "Kerala",
            pincode: "680101",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "4:30 AM - 10:00 PM",
            dailyTicketLimit: 600,
            ticketPrice: 20,
        },
        {
            name: "Padmanabhaswamy Temple",
            description: "A Hindu temple dedicated to Lord Vishnu located in Thiruvananthapuram. Known for its magnificent architecture and wealth.",
            location: "Thiruvananthapuram, Kerala",
            address: "Fort Palace Area, Thiruvananthapuram",
            city: "Thiruvananthapuram",
            state: "Kerala",
            pincode: "695033",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "3:30 AM - 10:30 PM",
            dailyTicketLimit: 500,
            ticketPrice: 30,
        },
        {
            name: "Vadakkumnathan Temple",
            description: "An ancient Hindu temple dedicated to Lord Shiva located in Thrissur. One of the oldest temples in Kerala with natural oil-based lamps.",
            location: "Thrissur, Kerala",
            address: "Vadakkumnathan Temple Road",
            city: "Thrissur",
            state: "Kerala",
            pincode: "680001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 12:30 PM, 4:00 PM - 8:00 PM",
            dailyTicketLimit: 350,
            ticketPrice: 15,
        },
        {
            name: "Kodungallur Bhagavathi Temple",
            description: "A Hindu temple dedicated to Goddess Bhagavathi located in Kodungallur. One of the oldest temples in Kerala with strong cultural significance.",
            location: "Kodungallur, Kerala",
            address: "Kodungallur Temple Road",
            city: "Kodungallur",
            state: "Kerala",
            pincode: "680667",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 12:00 PM, 6:00 PM - 8:00 PM",
            dailyTicketLimit: 250,
            ticketPrice: 10,
        },
        {
            name: "Mahakali Temple",
            description: "A Hindu temple dedicated to Goddess Kali located in Kolkata, West Bengal. An important site for Tantra traditions.",
            location: "Kalighat, Kolkata",
            address: "Kalighat Temple Road",
            city: "Kolkata",
            state: "West Bengal",
            pincode: "700025",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 9:00 PM",
            dailyTicketLimit: 400,
            ticketPrice: 15,
        },
        {
            name: "Dakshineswar Kali Temple",
            description: "A Hindu temple dedicated to Goddess Kali located on the Hooghly River. Associated with Sri Ramakrishna Paramahamsa.",
            location: "Dakshineswar, Kolkata",
            address: "Dakshineswar Temple Road",
            city: "Kolkata",
            state: "West Bengal",
            pincode: "700118",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 9:00 PM",
            dailyTicketLimit: 350,
            ticketPrice: 10,
        },
        {
            name: "Belur Math",
            description: "The headquarters of Ramakrishna Math and Ramakrishna Mission. Located on the Hooghly River, it is a center for spiritual learning.",
            location: "Belur, West Bengal",
            address: "Belur Math Road",
            city: "Belur",
            state: "West Bengal",
            pincode: "711202",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 11:00 AM, 3:30 PM - 6:00 PM",
            dailyTicketLimit: 300,
            ticketPrice: 0,
        },
        {
            name: "Jorakali Temple",
            description: "A historic Hindu temple dedicated to Goddess Jorakali in West Bengal. Known for its traditional Bengali architecture.",
            location: "Jorasanko, Kolkata",
            address: "Jorakali Temple Lane",
            city: "Kolkata",
            state: "West Bengal",
            pincode: "700007",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 8:00 PM",
            dailyTicketLimit: 200,
            ticketPrice: 10,
        },
        {
            name: "Mahalakshmi Temple",
            description: "A Hindu temple dedicated to Goddess Mahalakshmi located in Mumbai. One of the most important temples in Maharashtra.",
            location: "Mahim, Mumbai",
            address: "Mahalakshmi Temple Road",
            city: "Mumbai",
            state: "Maharashtra",
            pincode: "400016",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 11:00 PM",
            dailyTicketLimit: 450,
            ticketPrice: 0,
        },
        {
            name: "Vishnu Temple, Khajuraho",
            description: "A beautiful temple complex in Khajuraho known for its ornate sculptures and Dravidian architecture.",
            location: "Khajuraho, Madhya Pradesh",
            address: "Khajuraho Temple Complex",
            city: "Khajuraho",
            state: "Madhya Pradesh",
            pincode: "471606",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 6:00 PM",
            dailyTicketLimit: 300,
            ticketPrice: 40,
        },
        {
            name: "Sankat Mochan Temple",
            description: "A Hindu temple dedicated to Lord Hanuman located in Varanasi. Known for its spiritual importance and music performances.",
            location: "Varanasi, Uttar Pradesh",
            address: "Sankat Mochan Road",
            city: "Varanasi",
            state: "Uttar Pradesh",
            pincode: "221005",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 12:00 PM, 3:00 PM - 9:00 PM",
            dailyTicketLimit: 300,
            ticketPrice: 10,
        },
        {
            name: "Annapurna Temple",
            description: "A Hindu temple dedicated to Goddess Annapurna located in Varanasi. Symbolizes abundance and nourishment.",
            location: "Vishwanath Gali, Varanasi",
            address: "Annapurna Temple Road",
            city: "Varanasi",
            state: "Uttar Pradesh",
            pincode: "221001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "4:00 AM - 11:00 PM",
            dailyTicketLimit: 250,
            ticketPrice: 5,
        },
        {
            name: "Durga Temple, Varanasi",
            description: "A Hindu temple dedicated to Goddess Durga located in Varanasi. Known as the Monkey Temple due to the many monkeys.",
            location: "Panchkot, Varanasi",
            address: "Durga Temple Road",
            city: "Varanasi",
            state: "Uttar Pradesh",
            pincode: "221002",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 10:00 PM",
            dailyTicketLimit: 400,
            ticketPrice: 10,
        },
        {
            name: "Trimbakeshwar Temple",
            description: "A Hindu temple dedicated to Lord Shiva. One of the twelve Jyotirlingas located in Maharashtra.",
            location: "Trimbak, Maharashtra",
            address: "Trimbakeshwar Temple Road",
            city: "Nashik",
            state: "Maharashtra",
            pincode: "422208",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 11:00 PM",
            dailyTicketLimit: 500,
            ticketPrice: 30,
        },
        {
            name: "Rishikesh Temples",
            description: "A collection of sacred temples along the Ganges River in Rishikesh known for yoga and spirituality. Major pilgrimage destination.",
            location: "Rishikesh, Uttarakhand",
            address: "Rishikesh Temple Road",
            city: "Rishikesh",
            state: "Uttarakhand",
            pincode: "249201",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 10:00 PM",
            dailyTicketLimit: 600,
            ticketPrice: 20,
        },
        {
            name: "Haridwar Temples",
            description: "A collection of sacred temples in Haridwar, one of the holiest cities in Hinduism on the Ganges River.",
            location: "Haridwar, Uttarakhand",
            address: "Haridwar Temple Road",
            city: "Haridwar",
            state: "Uttarakhand",
            pincode: "249401",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 10:00 PM",
            dailyTicketLimit: 550,
            ticketPrice: 15,
        },
        {
            name: "Maa Vindhyavasini Temple",
            description: "A historic temple dedicated to Goddess Vindhyavasini located in Mirzapur. One of the 51 Shakti Peeths.",
            location: "Mirzapur, Uttar Pradesh",
            address: "Vindhyavasini Temple Road",
            city: "Mirzapur",
            state: "Uttar Pradesh",
            pincode: "231001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 10:00 PM",
            dailyTicketLimit: 400,
            ticketPrice: 20,
        },
        {
            name: "Kamakshya Temple",
            description: "An ancient temple dedicated to Goddess Kamakshya located in Guwahati, Assam. One of the 51 Shakti Peeths.",
            location: "Guwahati, Assam",
            address: "Kamakshya Temple Road",
            city: "Guwahati",
            state: "Assam",
            pincode: "781001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 10:00 PM",
            dailyTicketLimit: 500,
            ticketPrice: 25,
        },
        {
            name: "Navagraha Temple",
            description: "A temple dedicated to the nine planets (Navagraha) located in Guwahati. Built to pacify planetary influences.",
            location: "Guwahati, Assam",
            address: "Navagraha Temple Road",
            city: "Guwahati",
            state: "Assam",
            pincode: "781005",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 6:00 PM",
            dailyTicketLimit: 300,
            ticketPrice: 15,
        },
        {
            name: "Dhumavati Temple",
            description: "A temple dedicated to Dhumavati, the widow form of Durga. Located in Varanasi, it is a significant site for Tantric worship.",
            location: "Varanasi, Uttar Pradesh",
            address: "Dhumavati Lane",
            city: "Varanasi",
            state: "Uttar Pradesh",
            pincode: "221005",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 10:00 PM",
            dailyTicketLimit: 200,
            ticketPrice: 5,
        },
        {
            name: "Jyotiba Phule Temple",
            description: "A temple located in the Kolhapur district of Maharashtra dedicated to Jyotiba, a form of Shiva.",
            location: "Kolhapur, Maharashtra",
            address: "Jyotiba Temple Road",
            city: "Kolhapur",
            state: "Maharashtra",
            pincode: "416001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 8:00 PM",
            dailyTicketLimit: 350,
            ticketPrice: 20,
        },
        {
            name: "Mahakaleshwar Temple",
            description: "A Hindu temple dedicated to Lord Shiva. One of the twelve Jyotirlingas located in Ujjain, Madhya Pradesh.",
            location: "Ujjain, Madhya Pradesh",
            address: "Mahakal Lok Road",
            city: "Ujjain",
            state: "Madhya Pradesh",
            pincode: "456010",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 11:00 PM",
            dailyTicketLimit: 600,
            ticketPrice: 40,
        },
        {
            name: "Omkareshwar Temple",
            description: "A Hindu temple dedicated to Lord Shiva. One of the twelve Jyotirlingas located on the Narmada River.",
            location: "Indore, Madhya Pradesh",
            address: "Omkareshwar Temple Road",
            city: "Indore",
            state: "Madhya Pradesh",
            pincode: "458330",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:00 AM - 10:00 PM",
            dailyTicketLimit: 450,
            ticketPrice: 35,
        },
        {
            name: "Manakamana Temple",
            description: "A temple dedicated to Goddess Bhagwati (Almighty) located in the Himalayas. Accessible by cable car.",
            location: "Gorkha, Nepal (near India)",
            address: "Manakamana Temple Road",
            city: "Gorkha",
            state: "Nepal",
            pincode: "25100",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 6:00 PM",
            dailyTicketLimit: 400,
            ticketPrice: 45,
        },
        {
            name: "Ekling Ji Temple",
            description: "A Hindu temple dedicated to Lord Shiva in Mewar. Also known as Lord of Mewar's family deity.",
            location: "Udaipur, Rajasthan",
            address: "Ekling Ji Temple Road",
            city: "Udaipur",
            state: "Rajasthan",
            pincode: "313001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "5:30 AM - 10:30 PM",
            dailyTicketLimit: 300,
            ticketPrice: 20,
        },
        {
            name: "Jagdish Temple",
            description: "A Hindu temple dedicated to Lord Vishnu located in Udaipur. Built in the 17th century with beautiful architecture.",
            location: "Udaipur, Rajasthan",
            address: "Jagdish Temple Road",
            city: "Udaipur",
            state: "Rajasthan",
            pincode: "313001",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 1:00 PM, 4:00 PM - 10:00 PM",
            dailyTicketLimit: 350,
            ticketPrice: 15,
        },
        {
            name: "Charbhuja Temple",
            description: "A Hindu temple dedicated to Lord Krishna with beautiful architecture. Located in Rajasthan.",
            location: "Madhya Pradesh, Central India",
            address: "Charbhuja Temple Road",
            city: "Rajasthan",
            state: "Rajasthan",
            pincode: "331403",
            images: ["https://images.unsplash.com/photo-1437503713200-c2a395b3ef46?w=800"],
            timings: "6:00 AM - 9:00 PM",
            dailyTicketLimit: 250,
            ticketPrice: 15,
        },
    ];

    // Time slots template
    const timeSlots = [
        { startTime: "06:00", endTime: "08:00", capacity: 100 },
        { startTime: "08:00", endTime: "10:00", capacity: 100 },
        { startTime: "10:00", endTime: "12:00", capacity: 100 },
        { startTime: "14:00", endTime: "16:00", capacity: 100 },
        { startTime: "16:00", endTime: "18:00", capacity: 100 },
        { startTime: "18:00", endTime: "20:00", capacity: 100 },
    ];

    // Create temples with time slots
    for (const templeData of templesData) {
        const existingTemple = await prisma.temple.findFirst({
            where: { name: templeData.name },
        });

        if (existingTemple) {
            console.log(`⏭️  Temple already exists: ${templeData.name}`);
            continue;
        }

        const temple = await prisma.temple.create({
            data: {
                ...templeData,
                ownerId: templeBoard.id,
                timeSlots: {
                    create: timeSlots,
                },
            },
            include: {
                timeSlots: true,
            },
        });

        console.log(`🛕 Created temple: ${temple.name} with ${temple.timeSlots.length} time slots`);
    }

    console.log("\n✨ Seeding completed successfully!");
    console.log("\n📝 Test Accounts:");
    console.log("   Superuser: admin@templebook.com / admin123");
    console.log("   Temple Board: board@templebook.com / temple123");
    console.log("   Regular User: user@templebook.com / user123");
}

main()
    .catch((e) => {
        console.error("❌ Seeding failed:", e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });



